# Generated by Django 2.0.4 on 2018-07-07 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180706_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Comment'),
        ),
    ]
