# Generated by Django 2.0.4 on 2018-07-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image_file',
            field=models.FileField(default='', max_length=1000, upload_to='media/img'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', max_length=200, upload_to='media/video'),
        ),
    ]
