# Generated by Django 2.0.4 on 2018-07-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180707_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image_file',
            field=models.FileField(default='', max_length=1000, upload_to='C:\\nginx-1.14.0\\html\\html\\img'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', max_length=200, upload_to='C:\\nginx-1.14.0\\html\\html\\video'),
        ),
    ]
