# Generated by Django 2.0.4 on 2018-07-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180708_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='docm',
            field=models.CharField(default='', max_length=500, verbose_name='住宿'),
        ),
        migrations.AddField(
            model_name='video',
            name='food',
            field=models.CharField(default='', max_length=500, verbose_name='美食'),
        ),
        migrations.AddField(
            model_name='video',
            name='traffic',
            field=models.CharField(default='', max_length=500, verbose_name='交通'),
        ),
    ]
