# Generated by Django 2.0 on 2018-06-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0002_userinfo_llus_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='llus_num',
            new_name='us_num',
        ),
    ]
