# Generated by Django 2.0 on 2018-06-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0003_auto_20180619_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='us_num',
            new_name='attention_num',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='fs_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_fav_num',
            field=models.IntegerField(default=0),
        ),
    ]
