# Generated by Django 2.0.4 on 2018-06-28 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0004_auto_20180627_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree_or_not', models.BooleanField(default=False)),
                ('agree_time', models.IntegerField(default=0)),
                ('my_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_friend', to=settings.AUTH_USER_MODEL)),
                ('self_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
