# Generated by Django 2.0.4 on 2018-06-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0005_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='my_friend',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='self_user',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
