# Generated by Django 2.0.4 on 2018-07-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0006_auto_20180628_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='header_url',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
