# Generated by Django 2.0.4 on 2018-07-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0007_auto_20180716_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birth',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(default='', max_length=200),
        ),
    ]
